import type { SearchResult } from './types';

export const MOCK_SEARCH_RESULTS: SearchResult[] = [
  {
    id: 1,
    title: "GeneLab: Omics Database for Spaceflight Biology",
    url: "#",
    description: "GeneLab is a comprehensive database of genomics, transcriptomics, proteomics, and metabolomics data from spaceflight and corresponding ground control experiments.",
    summary: "GeneLab serves as a crucial open-access repository for 'omics' data related to space biology. It allows scientists to analyze how spaceflight affects organisms at a molecular level, covering genetics, proteins, and metabolites.",
    source: "NASA Open Science Data Repository",
    tags: ["genomics", "database", "omics"],
    publicationDate: "2023-05-15",
    authors: ["GeneLab Team", "S. Chakravarty"],
    type: "Dataset",
    species: ["Rodent", "Plant", "Microbe"],
    experimentType: "Microgravity",
    citationCount: 124,
    status: "Ongoing",
  },
  {
    id: 2,
    title: "Effects of Microgravity on the Human Cardiovascular System",
    url: "#",
    description: "A comprehensive review of the physiological changes observed in the cardiovascular system of astronauts during and after space missions. Focuses on fluid shifts, cardiac atrophy, and orthostatic intolerance.",
    summary: "This review details how the absence of gravity affects the human heart and blood vessels. Key issues discussed include the upward shift of body fluids, a slight decrease in heart size, and dizziness upon returning to Earth (orthostatic intolerance).",
    source: "NASA Space Life Sciences Library",
    tags: ["cardiovascular", "human research"],
    publicationDate: "2022-11-20",
    authors: ["Michael B. Stenger", "Steven S. Laurie"],
    type: "Literature Review",
    species: ["Human"],
    experimentType: "Microgravity",
    citationCount: 258,
    status: null,
    journal: "Journal of Applied Physiology",
  },
  {
    id: 3,
    title: "Rodent Research-1 (RR-1) Mission Data",
    url: "#",
    description: "Experiment data from the RR-1 mission, studying the effects of spaceflight on mouse physiology, including bone density, muscle mass, and immune response.",
    summary: "The RR-1 mission provided valuable data on how spaceflight impacts mammalian physiology. Analysis of the rodent subjects showed significant changes in bone density, muscle atrophy, and alterations in immune system function.",
    source: "NASA Task Book",
    tags: ["rodent research", "physiology"],
    publicationDate: "2021-09-01",
    authors: ["NASA Ames Research Center"],
    type: "Experimental",
    species: ["Rodent"],
    experimentType: "Microgravity",
    citationCount: 95,
    status: "Completed",
    journal: "Nature Space",
  },
  {
    id: 4,
    title: "Plant Signaling and Behavior in Microgravity",
    url: "#",
    description: "This publication explores how plants perceive and respond to gravity, and how these mechanisms are altered in a microgravity environment, impacting growth and development.",
    summary: "Plants use gravity as a reference for growth. This paper examines the molecular and behavioral changes in plants when this reference is removed in microgravity, affecting root orientation, nutrient uptake, and overall development.",
    source: "Open-access Space Biology Publications",
    tags: ["plants", "signaling", "behavior"],
    publicationDate: "2021-03-12",
    authors: ["John Z. Kiss", "Richard E. Edelmann"],
    type: "Publication",
    species: ["Plant"],
    experimentType: "Microgravity",
    citationCount: 188,
    status: null,
  },
  {
    id: 5,
    title: "Microbial Tracking in the International Space Station (ISS)",
    url: "#",
    description: "A study identifying and tracking microbial populations on the ISS to understand how they adapt to the space environment and to assess potential risks to crew health.",
    summary: "This research catalogues the diverse community of microbes living aboard the ISS. By monitoring these populations over time, scientists can assess risks to astronaut health and equipment integrity, and study microbial adaptation to extreme environments.",
    source: "NASA Open Science Data Repository",
    tags: ["microbiology", "ISS", "crew health"],
    publicationDate: "2024-01-22",
    authors: ["Kasthuri Venkateswaran", "George E. Fox"],
    type: "Publication",
    species: ["Microbe"],
    experimentType: "Hardware Validation",
    citationCount: 72,
    status: "Ongoing",
  },
  {
    id: 6,
    title: "Human Research Program: Space Radiation Effects on Humans",
    url: "#",
    description: "An overview of NASA's research into the health risks posed by space radiation, including cancer, central nervous system effects, and degenerative diseases.",
    summary: "Space radiation is a major health concern for long-duration missions. This program overview outlines NASA's strategy for studying and mitigating risks like increased cancer likelihood, potential damage to the central nervous system, and other degenerative conditions.",
    source: "NASA Human Research Program",
    tags: ["radiation", "human research", "health risk"],
    publicationDate: "2023-08-30",
    authors: ["Human Research Program Team"],
    type: "Literature Review",
    species: ["Human"],
    experimentType: "Radiation",
    citationCount: 310,
    status: null,
  },
  {
    id: 7,
    title: "Advanced Resistive Exercise Device (ARED) Efficacy",
    url: "#",
    description: "Analysis of the ARED's effectiveness in mitigating bone and muscle loss in astronauts on the International Space Station.",
    summary: "The Advanced Resistive Exercise Device (ARED) is a key piece of equipment on the ISS for combating musculoskeletal deconditioning. This study analyzes its success in helping astronauts maintain bone density and muscle mass during long-term spaceflight.",
    source: "NASA Task Book",
    tags: ["exercise", "countermeasures", "ISS"],
    publicationDate: "2020-07-19",
    authors: ["Scott M. Smith", "Lori L. Ploutz-Snyder"],
    type: "Experimental",
    species: ["Human"],
    experimentType: "Countermeasures",
    citationCount: 203,
    status: "Completed",
    journal: "Aerospace Medicine and Human Performance",
  },
  {
    id: 8,
    title: "VEG-01: Vegetable Production System on the ISS",
    url: "#",
    description: "Data and findings from the 'Veggie' hardware validation, which involved growing 'Outredgeous' red romaine lettuce on the ISS.",
    summary: "The VEG-01 experiment successfully demonstrated the capability of growing edible plants in space. This dataset includes growth metrics, microbial safety analysis, and crew feedback on the lettuce grown aboard the ISS, paving the way for future space agriculture.",
    source: "NASA Open Science Data Repository",
    tags: ["plants", "food production", "ISS"],
    publicationDate: "2019-02-11",
    authors: ["Gioia D. Massa", "Robert C. Morrow"],
    type: "Dataset",
    species: ["Plant"],
    experimentType: "Hardware Validation",
    citationCount: 150,
    status: "Completed",
  },
  {
    id: 9,
    title: "Meta-Analysis of Gene Expression Changes in Spaceflight",
    url: "#",
    description: "A meta-analysis of multiple transcriptomics datasets from GeneLab to identify common molecular pathways affected by microgravity across different species.",
    summary: "This study aggregates data from various spaceflight experiments to find consistent patterns in gene expression. The analysis points to key biological processes, like immune response and oxidative stress, that are universally affected by the space environment.",
    source: "GeneLab",
    tags: ["meta-analysis", "genomics", "transcriptomics"],
    publicationDate: "2024-03-10",
    authors: ["Egle Cekanaviciute", "Lauren M. Sanders"],
    type: "Meta-Analysis",
    species: ["Rodent", "Human", "Plant"],
    experimentType: "Microgravity",
    citationCount: 45,
    status: null,
    journal: "Cell Reports"
  }
];

export const SOURCES = [...new Set(MOCK_SEARCH_RESULTS.map(r => r.source))];
export const TYPES = [...new Set(MOCK_SEARCH_RESULTS.map(r => r.type))];
export const SPECIES = [...new Set(MOCK_SEARCH_RESULTS.flatMap(r => r.species))];
export const EXPERIMENT_TYPES = [...new Set(MOCK_SEARCH_RESULTS.map(r => r.experimentType))];
